---
title: "Exploração dos dados das vias-cg"
author: "Pedro Lira"
date: "7 de junho de 2018"
output: html_document
---
```{r echo=FALSE, warning=FALSE} 
library(tidyverse)
library(here)
library(viridis)
library(colourlovers)
library(skimr)
library(viridisLite)
library(plotly)

source(here::here("code/theme_report.R"))
source(here::here("code/read_wrangle.R"))
source(here::here("code/import_data.R"))


theme_set(theme_report())
knitr::opts_chunk$set(tidy = FALSE,
                      fig.width = 6,
                      fig.height = 5,
                      echo = FALSE)
options(scipen = 999)

```


```{r read}
vias = read_wrangle_data()
```


## Sumarizando os dados

```{r warning=FALSE}
sumario_vias_prof <- vias %>%
    filter(!is.na(profissao)) %>% 
    group_by(tipo_profissao) %>%
    summarise(num_vias = n(),
              media_km = (sum(comprimento)/1000)/num_vias,
              arvores_por_km = sum(arvore)/media_km,
              bancos_por_km = sum(bancos)/media_km,
              ponto_onibus_por_km = sum(pontoonibu)/media_km,
              ponto_taxi_por_km = sum(pontotaxi)/media_km,
              pontomotot = sum(pontomotot)/media_km,
              faixas_por_km = sum(faixapedes)/media_km)
```

```{r}
sumario_vias_prof %>%
    plot_ly(width = 600, height = 200) %>%
    add_trace(type = 'parcoords',
          line = list(color = ~tipo_profissao,
                      showscale=TRUE,
            dimensions = list(
            list(range = c(~min(num_vias),~max(num_vias)),
                 constraintrange = c(1, 100),
                 label = '# Vias',
                 values = ~num_vias),
            list(range = c(~min(arvores_por_km),~max(arvores_por_km)),
                 constraintrange = c(1, 100),
                 label = '# Vias',
                 values = ~arvores_por_km)
            #list(range = c(~min(media_km),~max(media_km)),
            #    label = 'Média de KM/Via', values = ~media_km),
            #list(range = c(~min(arvores_por_km),~max(arvores_por_km)),
            #     label = 'Árvores por KM/Via', values = ~arvores_por_km),
            #list(label = 'Bancos por KM/Via', values = ~bancos_por_km)
            )
          )
  )
```
